# 34f2101daf2e6f784af34a3886cf12e46e682c77 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2020-10-18 23:25:18 +0800 for /mnt/Vault/08.Dev/01.Workspaces/gvcs_fx/fx/main.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT8ddb51389a2b397bc522e19742d9c9811ba804a0
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneLayout::VBox) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 getChildren.add(build(Java::JavafxSceneControl::SplitPane) do
  getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
   getChildren.add(build(Java::JavafxSceneLayout::GridPane) do
    getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
     setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
     setMaxWidth(194.0)
     setMinWidth(10.0)
     setPrefWidth(186.0)
    end)
    getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
     setHgrow(Java::javafx::scene::layout::Priority::ALWAYS)
     setMaxWidth(1.7976931348623157e+308)
     setMinWidth(10.0)
     setPrefWidth(686.0)
    end)
    getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
     setHgrow(Java::javafx::scene::layout::Priority::NEVER)
     setMaxWidth(176.0)
     setMinWidth(10.0)
     setPrefWidth(176.0)
    end)
    getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
     setMinHeight(-Infinity)
     setPrefHeight(38.0)
     setVgrow(Java::javafx::scene::layout::Priority::NEVER)
    end)
    getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
     setMinHeight(10.0)
     setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
    end)
    getChildren.add(build(Java::JavafxSceneControl::TitledPane) do
     setContent(build(Java::JavafxSceneControl::TableView) do
      setId("tblWorkspaces")
      __local_fx_id_setter.call("tblWorkspaces", self)
      getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
       setPrefWidth(75.0)
       setText("C1")
      end)
      getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
       setPrefWidth(75.0)
       setText("C2")
      end)
      setMaxHeight(1.7976931348623157e+308)
      setMaxWidth(1.7976931348623157e+308)
      setOnDragDropped(EventHandlerWrapper.new(__local_fxml_controller, "workspace_dnd_dropped"))
      setOnDragOver(EventHandlerWrapper.new(__local_fxml_controller, "workspace_dnd_over"))
      setOnKeyReleased(EventHandlerWrapper.new(__local_fxml_controller, "workspace_key_released"))
     end)
     setCollapsible(false)
     setMaxHeight(1.7976931348623157e+308)
     setMaxWidth(1.7976931348623157e+308)
     setText("Managed Workspace(s)")
     Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 3)
     Java::JavafxSceneLayout::GridPane.setRowIndex(self, 1)
     Java::JavafxSceneLayout::GridPane.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
    end)
    getChildren.add(build(Java::JavafxSceneControl::TextField) do
     setId("txtWorkspacePath")
     __local_fx_id_setter.call("txtWorkspacePath", self)
     Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"right"=>"5.0"}, Java::JavafxGeometry::Insets) do
     end)
     setPromptText("Workspace path")
     Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
    end)
    getChildren.add(build(Java::JavafxSceneLayout::HBox) do
     getChildren.add(build(Java::JavafxSceneControl::Button) do
      setId("butOpenWorkspace")
      __local_fx_id_setter.call("butOpenWorkspace", self)
      setMaxWidth(80.0)
      setMinWidth(80.0)
      setMnemonicParsing(false)
      setPrefWidth(80.0)
      setText("Open")
      setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "open_workspace"))
     end)
     getChildren.add(build(Java::JavafxSceneControl::Button) do
      setId("butAddWorkspace")
      __local_fx_id_setter.call("butAddWorkspace", self)
      Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"left"=>"5.0"}, Java::JavafxGeometry::Insets) do
      end)
      setMaxWidth(80.0)
      setMinWidth(80.0)
      setMnemonicParsing(false)
      setPrefWidth(80.0)
      setText("Add")
      setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "workspace_add"))
     end)
     setAlignment(Java::javafx::geometry::Pos::CENTER_LEFT)
     Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 2)
     Java::JavafxSceneLayout::GridPane.setHalignment(self, Java::javafx::geometry::HPos::CENTER)
    end)
    Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
   end)
   setMinHeight(0.0)
   setMinWidth(0.0)
   setPrefHeight(100.0)
   setPrefWidth(160.0)
  end)
  getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
   getChildren.add(build(Java::JavafxSceneLayout::StackPane) do
    setId("pnlStack")
    __local_fx_id_setter.call("pnlStack", self)
    getChildren.add(build(Java::JavafxSceneLayout::GridPane) do
     setId("pnlLanding")
     __local_fx_id_setter.call("pnlLanding", self)
     getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
      setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
      setMinWidth(10.0)
      setPrefWidth(100.0)
     end)
     getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
      setMinHeight(10.0)
      setPrefHeight(30.0)
      setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
     end)
     getChildren.add(build(Java::JavafxSceneControl::Label) do
      setId("txtLanding")
      __local_fx_id_setter.call("txtLanding", self)
      setFont(build(FxmlBuilderBuilder, {"size"=>"18.0"}, Java::JavafxSceneText::Font) do
      end)
      setText("Open a workspace or drag-and-drop workspace path here")
      setOnDragDropped(EventHandlerWrapper.new(__local_fxml_controller, "landing_dnd_dropped"))
      setOnDragOver(EventHandlerWrapper.new(__local_fxml_controller, "landing_dnd_over"))
      Java::JavafxSceneLayout::GridPane.setHalignment(self, Java::javafx::geometry::HPos::CENTER)
      Java::JavafxSceneLayout::GridPane.setValignment(self, Java::javafx::geometry::VPos::CENTER)
     end)
     setVisible(false)
     setOnDragDropped(EventHandlerWrapper.new(__local_fxml_controller, "landing_dnd_dropped"))
     setOnDragOver(EventHandlerWrapper.new(__local_fxml_controller, "landing_dnd_over"))
    end)
    getChildren.add(build(Java::JavafxSceneControl::TabPane) do
     setId("pnlDetails")
     __local_fx_id_setter.call("pnlDetails", self)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsState")
      __local_fx_id_setter.call("tabWsState", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       getChildren.add(build(Java::JavafxSceneLayout::GridPane) do
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::NEVER)
         setMaxWidth(215.0)
        end)
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         setMaxWidth(1.7976931348623157e+308)
         setMinWidth(10.0)
         setPrefWidth(684.0)
        end)
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         setMaxWidth(501.0)
         setMinWidth(10.0)
         setPrefWidth(209.0)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(118.0)
         setMinHeight(-Infinity)
         setPrefHeight(28.0)
         setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(1.7976931348623157e+308)
         setMinHeight(-Infinity)
         setVgrow(Java::javafx::scene::layout::Priority::ALWAYS)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(45.0)
         setMinHeight(10.0)
         setPrefHeight(38.0)
         setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(36.0)
         setMinHeight(10.0)
         setPrefHeight(33.0)
         setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
        end)
        getChildren.add(build(Java::JavafxSceneControl::Label) do
         setMaxHeight(-Infinity)
         setMinHeight(-Infinity)
         setText("Current Branch : ")
        end)
        getChildren.add(build(Java::JavafxSceneControl::Label) do
         setId("lblCurrBranch")
         __local_fx_id_setter.call("lblCurrBranch", self)
         setFont(build(FxmlBuilderBuilder, {"name"=>"System Italic", "size"=>"13.0"}, Java::JavafxSceneText::Font) do
         end)
         setMaxWidth(1.7976931348623157e+308)
         setPrefHeight(16.0)
         setText("<Select workspace>")
         Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 1)
         Java::JavafxSceneLayout::GridPane.setHgrow(self, Java::javafx::scene::layout::Priority::NEVER)
        end)
        getChildren.add(build(Java::JavafxSceneControl::TableView) do
         setId("tblChanges")
         __local_fx_id_setter.call("tblChanges", self)
         getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
          setPrefWidth(75.0)
          setText("C1")
         end)
         getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
          setPrefWidth(75.0)
          setText("C2")
         end)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"bottom"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
         end)
         setMaxWidth(1.7976931348623157e+308)
         setPrefHeight(200.0)
         Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 3)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 1)
        end)
        getChildren.add(build(Java::JavafxSceneControl::ComboBox) do
         setId("cmbCommitMsg")
         __local_fx_id_setter.call("cmbCommitMsg", self)
         setEditable(true)
         setMaxWidth(1.7976931348623157e+308)
         setPromptText("Commit message")
         setOnKeyTyped(EventHandlerWrapper.new(__local_fxml_controller, "is_cmbCommit_enter"))
         Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 3)
         Java::JavafxSceneLayout::GridPane.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 2)
        end)
        getChildren.add(build(Java::JavafxSceneControl::Button) do
         setId("butCommit")
         __local_fx_id_setter.call("butCommit", self)
         setDefaultButton(true)
         setMaxWidth(80.0)
         setMinWidth(80.0)
         setMnemonicParsing(false)
         setPrefWidth(80.0)
         setText("Commit")
         setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "vcs_commit"))
         Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 2)
         Java::JavafxSceneLayout::GridPane.setHalignment(self, Java::javafx::geometry::HPos::RIGHT)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 3)
        end)
        getChildren.add(build(Java::JavafxSceneLayout::HBox) do
         getChildren.add(build(Java::JavafxSceneControl::Button) do
          setId("butRefreshChanges")
          __local_fx_id_setter.call("butRefreshChanges", self)
          Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {}, Java::JavafxGeometry::Insets) do
          end)
          setAlignment(Java::javafx::geometry::Pos::CENTER)
          setMaxWidth(80.0)
          setMinWidth(80.0)
          setMnemonicParsing(false)
          setPrefWidth(80.0)
          setText("Refresh")
          setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "refresh_vcs_status"))
         end)
         setAlignment(Java::javafx::geometry::Pos::CENTER_RIGHT)
         setPrefHeight(100.0)
         setPrefWidth(200.0)
         Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 2)
        end)
        setLayoutX(240.0)
        setLayoutY(115.0)
        setMaxWidth(1.7976931348623157e+308)
        Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 8.0)
       end)
       setMinHeight(0.0)
       setMinWidth(0.0)
       setPrefHeight(180.0)
       setPrefWidth(200.0)
      end)
      setText("State")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsIgnoreRules")
      __local_fx_id_setter.call("tabWsIgnoreRules", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       getChildren.add(build(Java::JavafxSceneControl::TitledPane) do
        setContent(build(Java::JavafxSceneLayout::GridPane) do
         getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
          setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
          setMinWidth(10.0)
          setPrefWidth(100.0)
         end)
         getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
          setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
          setMinWidth(10.0)
          setPrefWidth(100.0)
         end)
         getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
          setMaxHeight(1.7976931348623157e+308)
          setMinHeight(-Infinity)
          setVgrow(Java::javafx::scene::layout::Priority::ALWAYS)
         end)
         getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
          setMaxHeight(150.0)
          setMinHeight(0.0)
          setPrefHeight(0.0)
          setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         end)
         getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
          setMinHeight(10.0)
          setPrefHeight(38.0)
          setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         end)
         getChildren.add(build(Java::JavafxSceneControl::TextArea) do
          setId("txtIgnoreRules")
          __local_fx_id_setter.call("txtIgnoreRules", self)
          setMaxHeight(1.7976931348623157e+308)
          setMaxWidth(1.7976931348623157e+308)
          setMinHeight(-Infinity)
          setMinWidth(-Infinity)
          Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
          Java::JavafxSceneLayout::GridPane.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
          Java::JavafxSceneLayout::GridPane.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         end)
         getChildren.add(build(Java::JavafxSceneLayout::HBox) do
          getChildren.add(build(Java::JavafxSceneControl::Button) do
           setId("butIgnoreListSave")
           __local_fx_id_setter.call("butIgnoreListSave", self)
           setMaxWidth(80.0)
           setMinWidth(80.0)
           setMnemonicParsing(false)
           setPrefWidth(80.0)
           setText("Save")
          end)
          setAlignment(Java::javafx::geometry::Pos::CENTER_RIGHT)
          setPrefHeight(100.0)
          setPrefWidth(200.0)
          Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 1)
          Java::JavafxSceneLayout::GridPane.setRowIndex(self, 2)
         end)
        end)
        setAnimated(false)
        setCollapsible(false)
        setLayoutX(335.0)
        setLayoutY(83.0)
        setText("Ignore Rules")
        Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 5.0)
        Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
        Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
        Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 8.0)
       end)
       setMinHeight(0.0)
       setMinWidth(0.0)
       setPrefHeight(180.0)
       setPrefWidth(200.0)
      end)
      setText("Ignore Rules")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsFiles")
      __local_fx_id_setter.call("tabWsFiles", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       getChildren.add(build(Java::JavafxSceneControl::TitledPane) do
        setContent(build(Java::JavafxSceneLayout::GridPane) do
         getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
          setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
          setMinWidth(10.0)
          setPrefWidth(100.0)
         end)
         getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
          setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
          setMinWidth(10.0)
          setPrefWidth(100.0)
         end)
         getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
          setMaxHeight(202.0)
          setMinHeight(10.0)
          setPrefHeight(34.0)
          setVgrow(Java::javafx::scene::layout::Priority::NEVER)
         end)
         getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
          setMaxHeight(1.7976931348623157e+308)
          setMinHeight(10.0)
          setVgrow(Java::javafx::scene::layout::Priority::ALWAYS)
         end)
         getChildren.add(build(Java::JavafxSceneControl::TreeTableView) do
          getColumns.add(build(Java::JavafxSceneControl::TreeTableColumn) do
           setPrefWidth(75.0)
           setText("C1")
          end)
          getColumns.add(build(Java::JavafxSceneControl::TreeTableColumn) do
           setPrefWidth(75.0)
           setText("C2")
          end)
          setPrefHeight(200.0)
          setPrefWidth(200.0)
          Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
          Java::JavafxSceneLayout::GridPane.setRowIndex(self, 1)
         end)
         getChildren.add(build(Java::JavafxSceneLayout::HBox) do
          getChildren.add(build(Java::JavafxSceneControl::Button) do
           setId("butFileRefresh")
           __local_fx_id_setter.call("butFileRefresh", self)
           setMaxWidth(80.0)
           setMinWidth(80.0)
           setMnemonicParsing(false)
           setPrefWidth(80.0)
           setText("Refresh")
           setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "refresh_files"))
          end)
          setAlignment(Java::javafx::geometry::Pos::CENTER_RIGHT)
          setPrefHeight(100.0)
          setPrefWidth(200.0)
          Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 1)
         end)
        end)
        setAnimated(false)
        setCollapsible(false)
        setLayoutX(186.0)
        setLayoutY(44.0)
        setText("File View")
        Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
        Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
        Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 8.0)
       end)
       setMinHeight(0.0)
       setMinWidth(0.0)
       setPrefHeight(180.0)
       setPrefWidth(200.0)
      end)
      setText("Files")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsBranches")
      __local_fx_id_setter.call("tabWsBranches", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       getChildren.add(build(Java::JavafxSceneLayout::GridPane) do
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::ALWAYS)
         setMinWidth(10.0)
         setPrefWidth(100.0)
        end)
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHalignment(Java::javafx::geometry::HPos::CENTER)
         setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         setMinWidth(10.0)
         setPrefWidth(100.0)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(1.7976931348623157e+308)
         setMinHeight(28.0)
         setPrefHeight(28.0)
         setVgrow(Java::javafx::scene::layout::Priority::NEVER)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(-Infinity)
         setMinHeight(-Infinity)
         setVgrow(Java::javafx::scene::layout::Priority::NEVER)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(-Infinity)
         setValignment(Java::javafx::geometry::VPos::CENTER)
         setVgrow(Java::javafx::scene::layout::Priority::NEVER)
        end)
        getChildren.add(build(Java::JavafxSceneControl::Label) do
         setText("Workspace Branches:")
        end)
        getChildren.add(build(Java::JavafxSceneControl::ListView) do
         setId("lstBranches")
         __local_fx_id_setter.call("lstBranches", self)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"bottom"=>"5.0"}, Java::JavafxGeometry::Insets) do
         end)
         setOnMouseClicked(EventHandlerWrapper.new(__local_fxml_controller, "branch_clicked"))
         Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
         Java::JavafxSceneLayout::GridPane.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 1)
        end)
        getChildren.add(build(Java::JavafxSceneControl::TextField) do
         setId("txtNewBranchName")
         __local_fx_id_setter.call("txtNewBranchName", self)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"bottom"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
         end)
         setMinHeight(28.0)
         setPrefHeight(28.0)
         setPromptText("New branch name")
         Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
         Java::JavafxSceneLayout::GridPane.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 2)
        end)
        getChildren.add(build(Java::JavafxSceneControl::Button) do
         setId("butCreateBranch")
         __local_fx_id_setter.call("butCreateBranch", self)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"3.0"}, Java::JavafxGeometry::Insets) do
         end)
         setMinWidth(80.0)
         setMnemonicParsing(false)
         setPrefWidth(80.0)
         setText("Create")
         setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "create_branch"))
         Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 1)
         Java::JavafxSceneLayout::GridPane.setHalignment(self, Java::javafx::geometry::HPos::RIGHT)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 3)
         Java::JavafxSceneLayout::GridPane.setValignment(self, Java::javafx::geometry::VPos::CENTER)
        end)
        setLayoutX(421.0)
        setLayoutY(175.0)
        Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 8.0)
       end)
       setMinHeight(0.0)
       setMinWidth(0.0)
       setPrefHeight(180.0)
       setPrefWidth(200.0)
      end)
      setText("Branches")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsTags")
      __local_fx_id_setter.call("tabWsTags", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       getChildren.add(build(Java::JavafxSceneLayout::GridPane) do
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         setMinWidth(10.0)
         setPrefWidth(100.0)
        end)
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         setMinWidth(10.0)
         setPrefWidth(100.0)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(178.0)
         setMinHeight(-Infinity)
         setPrefHeight(28.0)
         setVgrow(Java::javafx::scene::layout::Priority::NEVER)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(1.7976931348623157e+308)
         setVgrow(Java::javafx::scene::layout::Priority::ALWAYS)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMinHeight(-Infinity)
         setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMinHeight(10.0)
         setPrefHeight(30.0)
         setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
        end)
        getChildren.add(build(Java::JavafxSceneControl::Label) do
         setText("Tags Defined :")
        end)
        getChildren.add(build(Java::JavafxSceneControl::ListView) do
         setId("lstTags")
         __local_fx_id_setter.call("lstTags", self)
         setPrefHeight(200.0)
         setPrefWidth(200.0)
         Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
         Java::JavafxSceneLayout::GridPane.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 1)
        end)
        getChildren.add(build(Java::JavafxSceneControl::TextField) do
         setId("txtNewTagName")
         __local_fx_id_setter.call("txtNewTagName", self)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"bottom"=>"8.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
         end)
         setMinWidth(28.0)
         setPrefWidth(28.0)
         setPromptText("New Tag")
         Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 2)
        end)
        getChildren.add(build(Java::JavafxSceneControl::Button) do
         setId("butCreateTag")
         __local_fx_id_setter.call("butCreateTag", self)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {}, Java::JavafxGeometry::Insets) do
         end)
         setMinWidth(80.0)
         setMnemonicParsing(false)
         setPrefWidth(80.0)
         setText("Create")
         setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "create_tag"))
         Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 1)
         Java::JavafxSceneLayout::GridPane.setHalignment(self, Java::javafx::geometry::HPos::RIGHT)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 3)
        end)
        setLayoutX(382.0)
        setLayoutY(198.0)
        Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 8.0)
       end)
       setMinHeight(0.0)
       setMinWidth(0.0)
       setPrefHeight(180.0)
       setPrefWidth(200.0)
      end)
      setText("Tags")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsConfig")
      __local_fx_id_setter.call("tabWsConfig", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       getChildren.add(build(Java::JavafxSceneLayout::GridPane) do
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         setMinWidth(10.0)
         setPrefWidth(100.0)
        end)
        getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
         setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         setMinWidth(10.0)
         setPrefWidth(100.0)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMaxHeight(1.7976931348623157e+308)
         setVgrow(Java::javafx::scene::layout::Priority::ALWAYS)
        end)
        getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
         setMinHeight(10.0)
         setPrefHeight(38.0)
         setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
        end)
        getChildren.add(build(Java::JavafxSceneControl::TitledPane) do
         setContent(build(Java::JavafxSceneControl::TabPane) do
          getTabs.add(build(Java::JavafxSceneControl::Tab) do
           setContent(build(Java::JavafxSceneControl::SplitPane) do
            getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
             getChildren.add(build(Java::JavafxSceneLayout::VBox) do
              getChildren.add(build(Java::JavafxSceneControl::Label) do
               setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
               end)
               setText("Global Keys")
              end)
              getChildren.add(build(Java::JavafxSceneControl::ListView) do
               setId("lstGlobalConfigKey")
               __local_fx_id_setter.call("lstGlobalConfigKey", self)
               Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
              end)
              setLayoutX(98.0)
              setLayoutY(77.0)
              Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
              Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
              Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
              Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
             end)
             setMaxWidth(280.0)
             setMinHeight(0.0)
             setMinWidth(100.0)
             setPrefWidth(180.0)
            end)
            getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
             getChildren.add(build(Java::JavafxSceneLayout::VBox) do
              getChildren.add(build(Java::JavafxSceneControl::Label) do
               setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
               end)
               setText("Values")
              end)
              getChildren.add(build(Java::JavafxSceneControl::TableView) do
               setId("tblGlobalConfigValues")
               __local_fx_id_setter.call("tblGlobalConfigValues", self)
               getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
                setPrefWidth(75.0)
                setText("C1")
               end)
               getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
                setPrefWidth(75.0)
                setText("C2")
               end)
               Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
              end)
              setLayoutX(251.0)
              setLayoutY(55.0)
              setPrefHeight(200.0)
              setPrefWidth(100.0)
              Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
              Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
              Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
              Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
             end)
             setMinHeight(0.0)
             setMinWidth(0.0)
             setPrefHeight(160.0)
             setPrefWidth(100.0)
            end)
            setDividerPositions(*[0.29797979797979796])
           end)
           setClosable(false)
           setText("Global")
          end)
          getTabs.add(build(Java::JavafxSceneControl::Tab) do
           setContent(build(Java::JavafxSceneLayout::AnchorPane) do
            getChildren.add(build(Java::JavafxSceneControl::SplitPane) do
             getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
              getChildren.add(build(Java::JavafxSceneLayout::VBox) do
               getChildren.add(build(Java::JavafxSceneControl::Label) do
                setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
                end)
                setText("Local Keys")
               end)
               getChildren.add(build(Java::JavafxSceneControl::ListView) do
                setId("lstLocalConfigKeys")
                __local_fx_id_setter.call("lstLocalConfigKeys", self)
                Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
               end)
               setLayoutX(148.0)
               setLayoutY(67.0)
               setPrefHeight(200.0)
               setPrefWidth(100.0)
               Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
               Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
               Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
               Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
              end)
              setMaxWidth(280.0)
              setMinHeight(0.0)
              setMinWidth(100.0)
              setPrefWidth(180.0)
             end)
             getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
              getChildren.add(build(Java::JavafxSceneLayout::VBox) do
               getChildren.add(build(Java::JavafxSceneControl::Label) do
                setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
                end)
                setText("Values")
               end)
               getChildren.add(build(Java::JavafxSceneControl::TableView) do
                setId("lstLocalConfigValues")
                __local_fx_id_setter.call("lstLocalConfigValues", self)
                getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
                 setPrefWidth(75.0)
                 setText("C1")
                end)
                getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
                 setPrefWidth(75.0)
                 setText("C2")
                end)
                Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
               end)
               setLayoutX(381.0)
               setLayoutY(62.0)
               setPrefHeight(200.0)
               setPrefWidth(100.0)
               Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
               Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
               Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
               Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
              end)
              setMinHeight(0.0)
              setMinWidth(0.0)
              setPrefHeight(160.0)
              setPrefWidth(100.0)
             end)
             setDividerPositions(*[0.29797979797979796])
             setLayoutX(290.0)
             setLayoutY(210.0)
             setPrefHeight(160.0)
             setPrefWidth(200.0)
             Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
             Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
             Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
             Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
            end)
            setMinHeight(0.0)
            setMinWidth(0.0)
            setPrefHeight(180.0)
            setPrefWidth(200.0)
           end)
           setClosable(false)
           setText("Local")
          end)
          setTabMinWidth(80.0)
         end)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"bottom"=>"5.0"}, Java::JavafxGeometry::Insets) do
         end)
         setCollapsible(false)
         setMaxHeight(1.7976931348623157e+308)
         setMinHeight(-Infinity)
         setText("Configurations")
         Java::JavafxSceneLayout::GridPane.setColumnSpan(self, 2)
         Java::JavafxSceneLayout::GridPane.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         Java::JavafxSceneLayout::GridPane.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
        end)
        getChildren.add(build(Java::JavafxSceneControl::Button) do
         setId("butConfigSave")
         __local_fx_id_setter.call("butConfigSave", self)
         Java::JavafxSceneLayout::GridPane.setMargin(self, build(FxmlBuilderBuilder, {"top"=>"5.0"}, Java::JavafxGeometry::Insets) do
         end)
         setContentDisplay(Java::javafx::scene::control::ContentDisplay::TOP)
         setMinWidth(80.0)
         setMnemonicParsing(false)
         setPrefWidth(80.0)
         setText("Save")
         Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 1)
         Java::JavafxSceneLayout::GridPane.setHalignment(self, Java::javafx::geometry::HPos::RIGHT)
         Java::JavafxSceneLayout::GridPane.setRowIndex(self, 1)
         Java::JavafxSceneLayout::GridPane.setValignment(self, Java::javafx::geometry::VPos::CENTER)
        end)
        setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0"}, Java::JavafxGeometry::Insets) do
        end)
        setLayoutX(385.0)
        setLayoutY(222.0)
        Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 8.0)
        Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 8.0)
       end)
       setMinHeight(0.0)
       setMinWidth(0.0)
      end)
      setText("Config")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsLogs")
      __local_fx_id_setter.call("tabWsLogs", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       getChildren.add(build(Java::JavafxSceneLayout::VBox) do
        getChildren.add(build(Java::JavafxSceneLayout::HBox) do
         getChildren.add(build(Java::JavafxSceneControl::Label) do
          setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
          end)
          setContentDisplay(Java::javafx::scene::control::ContentDisplay::TOP)
          setMaxWidth(1.7976931348623157e+308)
          setMinWidth(-Infinity)
          setPrefHeight(48.0)
          setPrefWidth(850.0)
          setText("Log Entries :")
          Java::JavafxSceneLayout::HBox.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         end)
         getChildren.add(build(Java::JavafxSceneControl::TextField) do
          setId("txtLogLimit")
          __local_fx_id_setter.call("txtLogLimit", self)
          setAlignment(Java::javafx::geometry::Pos::CENTER)
          setPromptText("Log limit")
          setOnKeyReleased(EventHandlerWrapper.new(__local_fxml_controller, "refresh_log"))
         end)
         setAlignment(Java::javafx::geometry::Pos::CENTER)
        end)
        getChildren.add(build(Java::JavafxSceneControl::TableView) do
         setId("tblLogs")
         __local_fx_id_setter.call("tblLogs", self)
         getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
          setPrefWidth(75.0)
          setText("C1")
         end)
         getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
          setPrefWidth(75.0)
          setText("C2")
         end)
         setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "right"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
         end)
         Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
        end)
        setLayoutX(489.0)
        setLayoutY(117.0)
        setPrefHeight(200.0)
        setPrefWidth(100.0)
        Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
        Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
        Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
        Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
       end)
       setMinHeight(0.0)
       setMinWidth(0.0)
       setPrefHeight(180.0)
       setPrefWidth(200.0)
      end)
      setText("Logs")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsRepos")
      __local_fx_id_setter.call("tabWsRepos", self)
      setContent(build(Java::JavafxSceneControl::TitledPane) do
       setContent(build(Java::JavafxSceneLayout::VBox) do
        getChildren.add(build(Java::JavafxSceneLayout::HBox) do
         getChildren.add(build(Java::JavafxSceneControl::TextField) do
          setId("txtReposName")
          __local_fx_id_setter.call("txtReposName", self)
          Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"right"=>"5.0"}, Java::JavafxGeometry::Insets) do
          end)
          setMaxWidth(180.0)
          setMinWidth(180.0)
          setPrefWidth(180.0)
          setPromptText("Repos name")
         end)
         getChildren.add(build(Java::JavafxSceneControl::TextField) do
          setId("txtReposUrl")
          __local_fx_id_setter.call("txtReposUrl", self)
          Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"right"=>"5.0"}, Java::JavafxGeometry::Insets) do
          end)
          setMaxWidth(1.7976931348623157e+308)
          setMinWidth(-Infinity)
          setPromptText("Repos URL")
          setOnKeyReleased(EventHandlerWrapper.new(__local_fxml_controller, "txtReposUrl_key_released"))
          Java::JavafxSceneLayout::HBox.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
         end)
         getChildren.add(build(Java::JavafxSceneControl::Button) do
          setId("butReposAdd")
          __local_fx_id_setter.call("butReposAdd", self)
          setMaxWidth(80.0)
          setMinWidth(80.0)
          setMnemonicParsing(false)
          setPrefWidth(80.0)
          setText("Add")
          setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "add_repository"))
         end)
         setAlignment(Java::javafx::geometry::Pos::CENTER_LEFT)
         setMaxWidth(1.7976931348623157e+308)
         setPrefHeight(34.0)
        end)
        getChildren.add(build(Java::JavafxSceneControl::TableView) do
         setId("tblRepos")
         __local_fx_id_setter.call("tblRepos", self)
         getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
          setPrefWidth(75.0)
          setText("C1")
         end)
         getColumns.add(build(Java::JavafxSceneControl::TableColumn) do
          setPrefWidth(75.0)
          setText("C2")
         end)
         Java::JavafxSceneLayout::VBox.setMargin(self, build(FxmlBuilderBuilder, {"bottom"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
         end)
         setPrefHeight(98.0)
         setOnKeyReleased(EventHandlerWrapper.new(__local_fxml_controller, "repos_key_released"))
        end)
        getChildren.add(build(Java::JavafxSceneLayout::GridPane) do
         getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
          setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
          setMinWidth(10.0)
          setPrefWidth(100.0)
         end)
         getColumnConstraints.add(build(Java::JavafxSceneLayout::ColumnConstraints) do
          setHalignment(Java::javafx::geometry::HPos::RIGHT)
          setHgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
          setMinWidth(10.0)
          setPrefWidth(100.0)
         end)
         getRowConstraints.add(build(Java::JavafxSceneLayout::RowConstraints) do
          setMinHeight(10.0)
          setPrefHeight(30.0)
          setVgrow(Java::javafx::scene::layout::Priority::SOMETIMES)
         end)
         getChildren.add(build(Java::JavafxSceneControl::Button) do
          setId("butReposPull")
          __local_fx_id_setter.call("butReposPull", self)
          setMaxWidth(80.0)
          setMinWidth(80.0)
          setMnemonicParsing(false)
          setPrefWidth(80.0)
          setText("Pull")
          setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "repos_pull"))
          Java::JavafxSceneLayout::GridPane.setColumnIndex(self, 1)
         end)
         getChildren.add(build(Java::JavafxSceneLayout::HBox) do
          getChildren.add(build(Java::JavafxSceneControl::Button) do
           setId("butReposPush")
           __local_fx_id_setter.call("butReposPush", self)
           Java::JavafxSceneLayout::HBox.setMargin(self, build(FxmlBuilderBuilder, {"right"=>"5.0"}, Java::JavafxGeometry::Insets) do
           end)
           setMaxWidth(80.0)
           setMinWidth(80.0)
           setMnemonicParsing(false)
           setPrefWidth(80.0)
           setText("Push")
           setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "repos_push"))
          end)
          getChildren.add(build(Java::JavafxSceneControl::CheckBox) do
           setId("chkPushWithTags")
           __local_fx_id_setter.call("chkPushWithTags", self)
           setMnemonicParsing(false)
           setText("with Tags")
          end)
          setAlignment(Java::javafx::geometry::Pos::CENTER_LEFT)
         end)
        end)
        setMaxWidth(1.7976931348623157e+308)
       end)
       setPadding(build(FxmlBuilderBuilder, {"top"=>"8.0"}, Java::JavafxGeometry::Insets) do
       end)
       setCollapsible(false)
       setText("Repository")
      end)
      setText("Repository")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsConflict")
      __local_fx_id_setter.call("tabWsConflict", self)
      setContent(build(Java::JavafxSceneLayout::HBox) do
       getChildren.add(build(Java::JavafxSceneControl::Label) do
        setFont(build(FxmlBuilderBuilder, {"name"=>"System Bold", "size"=>"24.0"}, Java::JavafxSceneText::Font) do
        end)
        setContentDisplay(Java::javafx::scene::control::ContentDisplay::CENTER)
        setText("Coming Soon")
       end)
       setAlignment(Java::javafx::geometry::Pos::CENTER)
       setPrefHeight(100.0)
       setPrefWidth(200.0)
      end)
      setText("Conflict")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     getTabs.add(build(Java::JavafxSceneControl::Tab) do
      setId("tabWsAction")
      __local_fx_id_setter.call("tabWsAction", self)
      setContent(build(Java::JavafxSceneLayout::AnchorPane) do
       setMinHeight(0.0)
       setMinWidth(0.0)
       setPrefHeight(180.0)
       setPrefWidth(200.0)
      end)
      setText("Action")
      setOnSelectionChanged(EventHandlerWrapper.new(__local_fxml_controller, "workspace_tab_changed"))
     end)
     setPadding(build(FxmlBuilderBuilder, {"top"=>"8.0"}, Java::JavafxGeometry::Insets) do
     end)
     setTabClosingPolicy(Java::javafx::scene::control::TabPane::TabClosingPolicy::UNAVAILABLE)
     setTabMinWidth(80.0)
    end)
    Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
    Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
   end)
   setMinHeight(0.0)
   setMinWidth(0.0)
   setPrefHeight(100.0)
   setPrefWidth(160.0)
  end)
  setDividerPositions(*[0.3])
  setOrientation(Java::javafx::geometry::Orientation::VERTICAL)
  setPrefHeight(200.0)
  setPrefWidth(160.0)
  Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
 end)
 getChildren.add(build(Java::JavafxSceneLayout::HBox) do
  getChildren.add(build(Java::JavafxSceneControl::Button) do
   setId("butClose")
   __local_fx_id_setter.call("butClose", self)
   setMaxWidth(80.0)
   setMinWidth(80.0)
   setMnemonicParsing(false)
   setPrefWidth(80.0)
   setText("Close")
   setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "winclose"))
  end)
  setAlignment(Java::javafx::geometry::Pos::CENTER_RIGHT)
  setMinHeight(-Infinity)
  setPrefHeight(38.0)
  setPrefWidth(584.0)
 end)
 setPadding(build(FxmlBuilderBuilder, {"bottom"=>"3.0", "left"=>"8.0", "right"=>"8.0", "top"=>"8.0"}, Java::JavafxGeometry::Insets) do
 end)
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(754.0)
 setPrefWidth(1065.0)
end
    end

      def hash
        "34f2101daf2e6f784af34a3886cf12e46e682c77"
      end
      def compiled?
        true
      end
    end
  end
end
